### ISSUE TITLE
[ BUG ] [ IOS ] getAppSignature  

### ISSUE THREAD

**Issue by Shiba-Kar** [surfstudio/flutter-otp-autofill#18]
## Describe the bug

Getting runtime error on calling .getAppSignature

```dart
_otpInteractor = OTPInteractor();
_otpInteractor.getAppSignature()
```
Unhandled Exception: Instance of 'UnsupportedPlatform'

**Comment by zaharovroman** [comment]
@Shiba-Kar 
On iOS OTP autofill is built in TextField. Code from sms stores for 3 minutes.
Rules for sms:
Sms must contain the word code or it translation to ios supported localizations.
Must be only one digit sequence in sms.
iOS Testing:
iOS can receive number from any other number.
