### ISSUE TITLE
OTP Send code again if haven't received any

### ISSUE THREAD

**Issue by BaudouinCS** [surfstudio/flutter-otp-autofill#21]
Hello,
I'd like to know if there is a way for the user to get another code in the case he hasn't received any.
If no, would it be possible to integrate it please?
Regards.

**Comment by MbIXjkee** [comment]
Hi! You can do it manual. When you has not received any code you can repeat all steps for get code. You can pass callback onTimeoutException to detect and process this situation.

**Comment by dshevchenkoo** [comment]
https://github.com/surfstudio/flutter-otp-autofill#send-new-code
