### ISSUE TITLE
Regenerating App Signature 

### ISSUE THREAD

**Issue by karangadani** [surfstudio/flutter-otp-autofill#27]
Hi, I just wanted to know that is there any way to generate new signature of the application ? 

Actually the problem with the once I got is that it contains a special character which is not accepted by the message service provider therefore startListenRetriever() is not working for me. 

Any solution to this would be appreciated!.

**Comment by zaharovroman** [comment]
@karangadani
The  application signature is generated by PackageManager (https://developer.android.com/reference/android/content/pm/PackageManager) object by package name. 
After that the hash is generated by the standard SHA-256 algorithm by package name and signature from the previous step. 
And this hash is used to get the OTP code.
So, we can't change this. 

It would help us a lot if you answered:
1. Which special character is contained in your hash? 
2. Did you check that the message service provider works correctly?

**Comment by karangadani** [comment]
@zaharovroman 
Thank you for your response.!

Actually I found a work around of this problem by my own. It's not an issue it was just a misunderstanding. 😅
