### ISSUE TITLE
Please update plugin to compatable with flutter 3.0.4

### ISSUE THREAD

**Issue by parmeetmaster** [surfstudio/flutter-otp-autofill#28]
We are facing issue to run app on flutter 3.0.4 sdk.This plugin unable to maintain compatabilty with other firebase plugin .

**Comment by dshevchenkoo** [comment]
We will update soon

**Comment by parmeetmaster** [comment]
Also please check Android 12 compatabilty

**Comment by zaharovroman** [comment]
@parmeetmaster We couldn't reproduce your issue with flutter 3.3.2 and and firebase_core 1.23.0 on Android 12 and 13 . 

Which versions of our package and firebase plugin  are you using?
 
And send your stacktrace, please.

**Comment by dshevchenkoo** [comment]
@parmeetmaster 
This package cannot have issues related to 3rd party Firebase plugins as there are no transitive dependencies.
Can you attach the stack trace containing the error?
