### ISSUE TITLE
Not Support on Kotlin version 1.5.20 or higher

### ISSUE THREAD

**Issue by umerbutt03** [surfstudio/flutter-otp-autofill#30]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':otp_autofill' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by zaharovroman** [comment]
@umerbutt03 
Which is your version of gradle dependency? 

Did you set minSdkVersion at least to 19 in <project root>/project/android/app/build.gradle?  (https://github.com/surfstudio/flutter-otp-autofill#android-installation)

Did it help you?

**Comment by Miracle-Blue** [comment]
I have the same error. my minSDKVersion is 21, downgrading to minSDKVersion 19 did not help. 
Can you update your package kotlin version, please?

**Comment by BaudouinCS** [comment]
@zaharovroman Hi, this issue currently makes the package **unusable** for anyone creating new projects or updating their old ones.
Nothing has been updated since 18 months so it might as well be branded as **not maintained anymore** to save everyone some headaches.
