### ISSUE TITLE
How to read a resend otp using this package

### ISSUE THREAD

**Issue by mohdasadkhan** [surfstudio/flutter-otp-autofill#33]
## Describe what scenario you think is uncovered by the existing examples / articles

A clear and concise description of the problem that you want explained.

## Describe why existing examples / articles do not cover this case

Explain which examples / articles you have seen before making this request, and
why they did not help you with your problem.

## Additional context

Add any other context or screenshots about the documentation request here.

**Comment by mark-kascheev** [comment]
Hello @mohdasadkhan! Use ```OTPTextEditController(autoStop: false)``` please, it might help.

**Comment by plasticfiresam** [comment]
Seems like there is solution for this issue, but there is no respond, so I close this issue as resolved

**Comment by singhmukesh2023** [comment]
@plasticfiresam  OTPTextEditController(autoStop: false) not work for resend OTP
