### ISSUE TITLE
[BUG] iOS always gets and Error called Unsupported Version

### ISSUE THREAD

**Issue by skumarpaSandy** [surfstudio/flutter-otp-autofill#40]
## Prior Issues
iOS platform not implemented

**Comment by GalimzyanovDanil** [comment]
@skumarpaSandy There is no need to use this package for iOS. This feature is out of the box in iOS. You just need to limit the use of the package on iOS so that you don't get errors. 
https://support.apple.com/guide/iphone/automatically-fill-in-sms-passcodes-iphc89a3a3af/ios

**Comment by skumarpaSandy** [comment]
OK, but we can listen the SMS at least right?,

any how, i have sorted out with my own method channel, thank you for the reply

**Comment by GalimzyanovDanil** [comment]
@skumarpaSandy iOS has not public API for reading SMS. Apple is very strict on this due to privacy concerns.
