### ISSUE TITLE
No found otp_surfstudio

### ISSUE THREAD

**Issue by saeedmpt** [surfstudio/flutter-otp-autofill#44]
No implementation found for method getAppSignature on channel otp_surfstudio

what is this problem? how to fix ?

**Comment by saeedmpt** [comment]
my code is 

    var _otpInteractor = OTPInteractor( );
    _otpInteractor.getAppSignature().then((value) => print('signature - $value'));

**Comment by GeekAbdelouahed** [comment]
try  `Flutter clean` then  `Flutter pub get` and run the app again.

**Comment by mark-kascheev** [comment]
@saeedmpt Did you resolve the problem?
