### ISSUE TITLE
Unable to import this package.

### ISSUE THREAD

**Issue by shwetha1295** [surfstudio/flutter-otp-autofill#48]
## Prior Issues

Are there any existing issues or PRs that relate to this problem? If so, link them here.

## Describe the bug

Please show the code you wrote as completely as possible.

```dart
/// your code here
```

## Steps to Reproduce

If the current behavior is a bug, please provide the steps to reproduce.

## Additional context

* What package and OS are affected by this issue? Did this work in previous versions of a package?
  
* If applicable, add screenshots to help explain your problem.

* Please provide output from `flutter doctor -v` and `flutter analyze`.
  
* Add any other context about the problem here.

**Comment by mark-kascheev** [comment]
@shwetha1295 Hello, fill the bug report template for more information please.
