### ISSUE TITLE
[BUG] Kotlin Gradle plugin Support

### ISSUE THREAD

**Issue by lopdam** [surfstudio/flutter-otp-autofill#53]
* What went wrong: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher. The following dependencies do not satisfy the required version: project ':otp_autofill' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by Dawid-Dlugosz** [comment]
The same issue
