### ISSUE TITLE
update kotlin to 1.7.10

### ISSUE THREAD

**Issue by MahdiForughi** [surfstudio/flutter-otp-autofill#55]
**The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':otp_autofill' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50**

**Comment by AgnelSelvan** [comment]
Hey @MahdiForughi ,
**How to test until it's merged**

```dart
dependencies:
  otp_autofill:
    git:
      url: https://github.com/AgnelSelvan/flutter-otp-autofill.git
      ref: master
```
