### ISSUE TITLE
Need to update the Koltin version to minimum 1.5.20

### ISSUE THREAD

**Issue by Deepak-811** [surfstudio/flutter-otp-autofill#67]
As flutter version is upgraded to 3.10.5 & Dart version 3.0.5 because of flutter & dart version is upgraded while building the app we are getting minimum kotlin version error.

Currently I am doing it manually.

Thanks.

**Comment by plasticfiresam** [comment]
Hello, @Deepak-811, thank you for your report.

Now we are working on publishing a new release of the plugin, in which this problem was fixed, stay tuned, I will separately tag you when the publication is completed

**Comment by maxim-sysoev** [comment]
@Deepak-811, We have released a new package version with upgraded kotlin to '1.7.21'
You can use the new major release of the plugin 3.0.0

**Comment by Deepak-811** [comment]
Thank you for your quick response.
