### ISSUE TITLE
[QUESTION] Can I remove/hide the popup of SMS?

### ISSUE THREAD

**Issue by kaushikbh99** [surfstudio/flutter-otp-autofill#94]
## Can I remove or hide SMS pop-up?
If it is possible, can anyone explain it here?

I want SMS code to auto-populate without any system popups.
I attached a screenshot below of the content I want to hide.

![Screenshot_2024-05-10-16-11-56-19_f7aa348215f5d566f9e4ca860f474209](https://github.com/surfstudio/flutter-otp-autofill/assets/106946397/9092b3dc-e8fa-4869-ad72-32c1d4e8b485)

**Comment by kaushikbh99** [comment]
> [Link to Pyrus task](https://pyrus.com/t#id215310864)

what is this?

**Comment by Jokerkras** [comment]
If you don't need this dialog, you should use another API - [SMS Retriever API](https://developers.google.com/identity/sms-retriever/overview). It is also in this library.
