### ISSUE TITLE
OTP autofill Not Working in IO

### ISSUE THREAD

**Issue by Amodh2022** [surfstudio/flutter-otp-autofill#95]
## Details

Flutter version: 

Dart version: 

Platform: 

## Checklist for self-check

- [ ] Added expected and actual behavior.
- [ ] Added video or screenshot of bug.
- [ ] Added isolated way to reproduce the bug.
- [ ] Specified Flutter, Dart version and platforms.
- [ ] Attached error code and logs.
- [ ] All unspecified fields in the Issue description are deleted.

**Comment by plasticfiresam** [comment]
Could you provide more information about your issue, please? @Amodh2022

**Comment by mpkander** [comment]
Closing the issue due to lack of details.
